# Generated by Django 5.0.4 on 2024-05-06 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=15)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.area')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=100)),
                ('prioridad', models.CharField(max_length=15)),
                ('estado', models.CharField(default='pendiente', max_length=15)),
                ('comenTecnico', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.area')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.empleado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.tecnico')),
            ],
        ),
    ]
