# Generated by Django 5.0.4 on 2024-06-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
