# Generated by Django 5.0.4 on 2024-05-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comenTecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
